#!/bin/bash

#CAF_HOME="/home/woelke/spideroak/working_dir/caf/actor-framework"
#FLAME_GRAPH_PATH="/home/woelke/spideroak/working_dir/caf/profiling/FlameGraph"
#BIN_PATH="${CAF_HOME}/build/bin"
#OUT_DIR="/home/woelke/spideroak/working_dir/caf/profiling"

CAF_HOME="/users/localadmin/woelke/actor-framework"
FLAME_GRAPH_PATH="/users/localadmin/woelke/FlameGraph"
BIN_PATH="${CAF_HOME}/build/bin"
OUT_DIR="/users/localadmin/woelke/test_data"

sudo sh -c "echo 0 > /proc/sys/kernel/kptr_restrict" 

cd $BIN_PATH
sudo perf record --all-cpus -g $@

cd $FLAME_GRAPH_PATH
sudo perf script --input="${BIN_PATH}/perf.data" | ./stackcollapse-perf.pl | ./flamegraph.pl > ${OUT_DIR}/flamegraph.svg

sudo sh -c "echo 1 > /proc/sys/kernel/kptr_restrict" 

duration=$SECONDS
echo "duration: $(($duration / 3600))h $((($duration / 60) % 60))m $(($duration % 60))s"
