#!/bin/bash

#CAF_HOME="/home/woelke/spideroak/working_dir/caf/actor-framework"
#FLAME_GRAPH_PATH="/home/woelke/spideroak/working_dir/caf/profiling/FlameGraph"
#BIN_PATH="${CAF_HOME}/build/bin"
#OUT_DIR="/home/woelke/spideroak/working_dir/caf/profiling"

CAF_HOME="/users/localadmin/woelke/actor-framework"
FLAME_GRAPH_PATH="/users/localadmin/woelke/FlameGraph"
BIN_PATH="${CAF_HOME}/build/bin"
OUT_DIR="/users/localadmin/woelke/test_data"

PERF_FILE="${OUT_DIR}/perf.data"
STACK_FILE="${OUT_DIR}/stack.data"
SVG_FILE="${OUT_DIR}/flamegraph.svg"

# Preperation
sudo sh -c "echo 0 > /proc/sys/kernel/kptr_restrict" 
rm -f ${OUT_DIR}/*

# record perf data
cd $BIN_PATH
sudo perf record --all-cpus -g --output=$PERF_FILE $@

# Convert perf data to svg
cd $FLAME_GRAPH_PATH
sudo perf script --input=$PERF_FILE | ./stackcollapse-perf.pl > $STACK_FILE
./flamegraph.pl > $SVG_FILE

# clean up
sudo sh -c "echo 1 > /proc/sys/kernel/kptr_restrict" 

duration=$SECONDS
echo "duration: $(($duration / 3600))h $((($duration / 60) % 60))m $(($duration % 60))s"
