#!/bin/bash
if [[ $(id -u) != 0 ]]; then
  echo "you need to be root"
  exit 0
fi

#CAF_HOME="/home/woelke/spideroak/working_dir/caf/actor-framework"
#FLAME_GRAPH_PATH="/home/woelke/spideroak/working_dir/caf/profiling/FlameGraph"
#BIN_PATH="${CAF_HOME}/build/bin"
#OUT_DIR="/home/woelke/spideroak/working_dir/caf/profiling"
#CAF_INI_FILE="caf-application.ini"

CAF_HOME="/users/localadmin/woelke/actor-framework"
BENCH_USER="localadmin"
FLAME_GRAPH_PATH="/users/localadmin/woelke/FlameGraph"
BIN_PATH="${CAF_HOME}/build/bin"
OUT_DIR="/users/localadmin/woelke/test_data"
CAF_INI_FILE="caf-application.ini"


# Preperation
#echo "Info: CAF should be compiled in debug mode"
rm -f ${OUT_DIR}/*

# Define records to do
#todo_array="stealing numa-steal"
todo_array="numa-steal"
declare -A bench_array
#bench_array["bencherl_12_timer_wheel;wheel"]="intermediate 50 wheel" #behavior without timeout
bench_array["savina_01_pingpong"]="-n 2400000"

set_bench_and_suffix() {
  IFS=';' read -ra ARGS_SUFFIX <<< "$1"
  bench=${ARGS_SUFFIX[0]}
  suffix=${ARGS_SUFFIX[1]}
  todo=$2
  if [ "$suffix" == "" ]; then
    suffix=${todo}
  else
    if [ "$todo" != "" ]; then
      suffix=${todo}-${suffix}
    fi
  fi
}

for bench_suffix in ${!bench_array[@]} ; do
for todo in $todo_array ; do
cat >${BIN_PATH}/${CAF_INI_FILE} <<EOL
[scheduler]
policy='$todo'
[numa]
neighborhood-level=2
EOL
  set_bench_and_suffix $bench_suffix $todo

  # record data with gperf
  cd $BIN_PATH
  output_file=${todo}_${bench}.gperf
  env CPUPROFILE=${OUT_DIR}/${output_file} CPUPROFILE_FREQUENCY=1000 ./${bench} ${bench_array[$bench_suffix]}

  # add requried infromation for gprof
  output_exe=${todo}_${bench}
  cp ${bench} ${OUT_DIR}/${output_exe}
done
done

duration=$SECONDS
echo "duration: $(($duration / 3600))h $((($duration / 60) % 60))m $(($duration % 60))s"
