#!/bin/bash

CAF_HOME="/users/localadmin/woelke/actor-framework"
OUT_DIR="/users/localadmin/woelke/test_data"
BIN_PATH="${CAF_HOME}/build/bin"
CAF_INI_FILE="caf-application.ini"
REPITITIONS=10

# Preperation
rm -f ${OUT_DIR}/*

todo_array="LGS;w-stealing;node;node; CLS-thread-pinning;stealing;system;system"
bench="numa_matrix_search_continues"
bench_args=""

unpack_props() {
  IFS=';' read -ra PROPS <<< "$1"
  name=${PROPS[0]}
  policy=${PROPS[1]}
  pinning_entity=${PROPS[2]}
  stealing_entity=${PROPS[3]}
}

# Run CAF benchmark suite
for todo_props in $todo_array ; do
  unpack_props $todo_props
cat >${BIN_PATH}/${CAF_INI_FILE} <<EOL
[scheduler]
policy='$policy'
[work-stealing]
aggressive-poll-attempts=100
aggressive-steal-interval=10
moderate-poll-attempts=500
moderate-steal-interval=5
moderate-sleep-duration=50
relaxed-steal-interval=1
relaxed-sleep-duration=10000
[lgs]
actor-pinning-entity='$pinning_entity'
w-stealing-entity='$stealing_entitiy'
EOL
  file="${bench}_${name}.txt"
  echo "sched_events, steal_attemps, success_steals" > $file
  echo "write to $file"
  for i in $(seq 0 $REPITITIONS); do
    printf "$i "
    ${BIN_PATH}/${bench} ${bench_args} > ${OUT_DIR}/$file 2>&1
  done
  #delete current line and move cursor to the beginning
  printf "\033[2K\r" 
done


duration=$SECONDS
echo "duration: $(($duration / 3600))h $((($duration / 60) % 60))m $(($duration % 60))s"
