#!/bin/bash
OUT_DIR="/users/localadmin/woelke/test_data"

# Preperation
rm -f ${OUT_DIR}/*

set_bench_and_suffix() {
  IFS=';' read -ra ARGS_SUFFIX <<< "$1"
  bench=${ARGS_SUFFIX[0]}
}

declare -A bench_args
#bench_args["savina_01_pingpong"]="-n 2000000"
#bench_args["savina_02_count"]="-n 10000000"
#bench_args["savina_03_fjthrput"]="-n 60000 -a 360"
#bench_args["savina_04_fjcreate"]="-n 4000000"
#bench_args["savina_05_threadring"]="-n 1200 -r 1200000"
#bench_args["savina_06_chameneos"]="-c 4000 -m 800000"
#bench_args["savina_07_big"]="-n 60000 -w 360"
bench_args["savina_08_concdict"]="-e 100 -m 50000"
bench_args["savina_09_concsll"]="-e 20 -m 8000"
#bench_args["savina_10_bndbuffer"]="-b 75 -p 60 -c 60 -i 1500"
#bench_args["savina_11_philosopher"]="-n 80 -m 40000"
###bench_args["savina_12_barber"]="-n 15000 -w 3000"
###bench_args["savina_13_cigsmok"]="-r 1000000 -s 200"
#bench_args["savina_14_logmap;NOCAF"]=""
#bench_args["savina_14_logmap_become_unbecome_fast;NOJAVA"]=""
#bench_args["savina_14_logmap_become_unbecome_slow;NOJAVA"]=""
#bench_args["savina_14_logmap_request_await_high_timeout;NOJAVA"]=""
#bench_args["savina_14_logmap_request_await_infinite;NOJAVA"]=""
#bench_args["savina_15_banking;NOCAF"]="-n 800000 -a 16000"
#bench_args["savina_15_banking_become_unbecome_fast;NOJAVA"]="-n 800000 -a 16000"
#bench_args["savina_15_banking_become_unbecome_slow;NOJAVA"]="-n 800000 -a 16000"
#bench_args["savina_15_banking_request_await_high_timeout;NOJAVA"]="-n 800000 -a 16000"
#bench_args["savina_15_banking_request_await_infinite;NOJAVA"]="-n 800000 -a 16000"
#bench_args["savina_15_banking_request_then_high_timeout;NOJAVA"]="-n 800000 -a 16000"
#bench_args["savina_15_banking_request_then_infinite;NOJAVA"]="-n 800000 -a 16000"
#bench_args["savina_16_radixsort"]="-n 400000"
###bench_args["savina_17_filterbank"]="-s 40000 -a 24"
#bench_args["savina_18_sieve"]="-n 2000000 -m 10000"
###bench_args["savina_19_uct"]=""
#bench_args["savina_20_facloc"]=" -n 200000 -g 1000"
#bench_args["savina_21_trapezoid"]="-w 4000 -n 400000000"
###bench_args["savina_22_piprecision"]=""
#bench_args["savina_23_recmatmul"]="-n 2048 -w 40"
#bench_args["savina_24_quicksort"]="-n 40000000"
#bench_args["savina_25_apsp"]="-n 900 -b 150 -w 300"
###bench_args["savina_26_sor"]=""
###bench_args["savina_27_astar"]=""
#bench_args["savina_28_nqueenk"]="-n 14 -w 100 -s 1500000"
#bench_args["savina_29_fib"]="-n 34"
#bench_args["savina_30_bitonicsort"]="-n 8192"

#bench_args["numa_matrix_search_continues"]=""

for bench_n_suffix in ${!bench_args[@]} ; do
  set_bench_and_suffix $bench_n_suffix
  ./run_steal_statistic ${bench} ${bench_args[$bench_n_suffix]}
done

duration=$SECONDS
echo "duration: $(($duration / 3600))h $((($duration / 60) % 60))m $(($duration % 60))s"
